spring:
  application:
    name: tenxdevs
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres.your-tenant-id
    password: your-super-secret-and-long-postgres-password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
#     Note: For production deployment, you might want to revert ddl-auto back to none and use proper database migrations (like Flyway or Liquibase) instead.
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect