spring:
  application:
    name: tenxdevs
  datasource:
    url: ${SUPABASE_DB_URL_LOCAL}
    username: ${SUPABASE_DB_USERNAME_LOCAL}
    password: ${SUPABASE_DB_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
#     Note: For production deployment, you might want to revert ddl-auto back to none and use proper database migrations (like Flyway or Liquibase) instead.
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}
          temperature: ${AI_TEMPERATURE}

supabase:
  url: ${SUPABASE_URL_LOCAL:http://localhost:54321}
  anon-key: ${SUPABASE_ANON_KEY_LOCAL}
  jwt-secret: ${SUPABASE_JWT_SECRET_LOCAL}

ai:
  usage:
    limit:
      daily: 10